spring.application.name=API_Gateway

server.port=8080

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

#Auth_Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0].name=CorrelationIdFilter

#Inventory_Service
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**, /customers/**
spring.cloud.gateway.routes[1].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[1].filters[1].name=CorrelationIdFilter

#Order_Service
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**, /invoices/**
spring.cloud.gateway.routes[2].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[2].filters[1].name=CorrelationIdFilter

#Report_Service
spring.cloud.gateway.routes[3].id=report-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/reports/**
spring.cloud.gateway.routes[3].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[3].filters[1].name=CorrelationIdFilter